name: Calendar sync

on:
  push:
    paths:
    - '.github/build-cop/schedule.yaml'

jobs:
  sync:
    # Only run this on repositories in the 'spinnaker' org, not on forks.
    if: startsWith(github.repository, 'spinnaker/')
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      uses: actions/checkout@v2

    - id: sync
      uses: spinnaker/rotation-scheduler@master
      with:
        args: |
          calendar sync --calendarID build-cop@spinnaker.io --jsonKey ${{ secrets.ROTATION_SCHEDULER_GCP_JSON_KEY }} .github/build-cop/schedule.yaml
